# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: acandocloud/webapp
  tag: 0.0.1
  pullPolicy: Always
service:
  enabled: true
  name: web
  type: ClusterIP
  url: webapp.kubernetes.acando-cloud.de
  externalPort: 80
  internalPort: 8080
postgresql:
  enabled: true
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi