apiVersion: v1
kind: Secret
metadata:
  name: webapp-db-secret
type: Opaque
data:
  username: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
